#pragma checksum "E:\asp.net\CBauerHW2\Order.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "67516A4FE948950F06A4704EC986A1F33331A5CB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Order : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.HyperLink HyperLink1;
    
    #line default
    #line hidden
    
    
    #line 40 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.TextBox nameTextBox;
    
    #line default
    #line hidden
    
    
    #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 47 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.TextBox phoneTextBox;
    
    #line default
    #line hidden
    
    
    #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
    
    #line default
    #line hidden
    
    
    #line 49 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
    
    #line default
    #line hidden
    
    
    #line 55 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.TextBox creditCardTextBox;
    
    #line default
    #line hidden
    
    
    #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;
    
    #line default
    #line hidden
    
    
    #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.ListBox itemListBox;
    
    #line default
    #line hidden
    
    
    #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
    
    #line default
    #line hidden
    
    
    #line 74 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.TextBox itemTextBox;
    
    #line default
    #line hidden
    
    
    #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
    
    #line default
    #line hidden
    
    
    #line 81 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.TextBox quantityTextBox;
    
    #line default
    #line hidden
    
    
    #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
    
    #line default
    #line hidden
    
    
    #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.RangeValidator RangeValidator1;
    
    #line default
    #line hidden
    
    
    #line 89 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.Label orderLabel;
    
    #line default
    #line hidden
    
    
    #line 94 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.Button addOrderButton;
    
    #line default
    #line hidden
    
    
    #line 97 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.WebControls.Button completeOrderButton;
    
    #line default
    #line hidden
    
    
    #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class order_aspx : global::Order, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.order_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public order_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\asp.net\CBauerHW2\Order.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Order.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.order_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Order.aspx";
                dependencies[1] = "~/Order.aspx.cs";
                global::ASP.order_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.order_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        90,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.order_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.order_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        185,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <style type=""text/css"">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 139px;
            text-align: right;
        }
        .auto-style3 {
            width: 139px;
            text-align: right;
            height: 30px;
        }
        .auto-style4 {
            height: 30px;
        }
    </style>
");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        200,
                        383,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 6 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        158,
                        432,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        590,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div>\r\n    \r\n        Order Page&nbsp; </div>\r\n        <table class=\"auto-st" +
                    "yle1\">\r\n            <tr>\r\n                <td class=\"auto-style2\">\r\n            " +
                    "        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        636,
                        169,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Homepage");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        880,
                        8,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlHyperLink1() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.HyperLink1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "HyperLink1";
            
            #line default
            #line hidden
            
            #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.NavigateUrl = "~/Default.aspx";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 34 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        805,
                        99,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style3\">Name:</td>\r\n                <td class=\"auto-style4\">\r\n     " +
                    "               ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        904,
                        176,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlnameTextBox() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 40 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.nameTextBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 40 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "nameTextBox";
            
            #line default
            #line hidden
            
            #line 40 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.nameTextBox_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1080,
                        99,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1179,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1336,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "nameTextBox";
            
            #line default
            #line hidden
            
            #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "Enter Your name";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 41 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1201,
                        165,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Phone Number:</td>\r\n                <td>\r\n                 " +
                    "   ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1366,
                        164,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlphoneTextBox() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 47 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.phoneTextBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "phoneTextBox";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1530,
                        60,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1590,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Please submit the phone number as (999) 999-9999");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1853,
                        48,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.RegularExpressionValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RegularExpressionValidator1";
            
            #line default
            #line hidden
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "phoneTextBox";
            
            #line default
            #line hidden
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "the phone number as (999) 999-9999";
            
            #line default
            #line hidden
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ValidationExpression = "((\\(\\d{3}\\) ?)|(\\d{3}-))?\\d{3}-\\d{4}";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 48 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1612,
                        322,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1934,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator5() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 49 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator5 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 49 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RequiredFieldValidator5";
            
            #line default
            #line hidden
            
            #line 49 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "phoneTextBox";
            
            #line default
            #line hidden
            
            #line 49 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "enter your phone number";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1956,
                        173,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">credit card number:</td>\r\n                <td>\r\n           " +
                    "         ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2129,
                        170,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlcreditCardTextBox() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 55 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.creditCardTextBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 55 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "creditCardTextBox";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2299,
                        65,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2364,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Enter your sixteen digit card number");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2587,
                        36,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator2() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.RegularExpressionValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RegularExpressionValidator2";
            
            #line default
            #line hidden
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "creditCardTextBox";
            
            #line default
            #line hidden
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "Invalid card number";
            
            #line default
            #line hidden
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ValidationExpression = "\\d{16}";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 56 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2386,
                        270,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Item:</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2656,
                        156,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 63 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 63 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Pen";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 64 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 64 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Mouse pad";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control23() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 65 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 65 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Picture Frame";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control24() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 66 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 66 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Mug";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control20(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl2 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl3 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl4 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListBox @__BuildControlitemListBox() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            
            #line default
            #line hidden
            this.itemListBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "itemListBox";
            
            #line default
            #line hidden
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            this.@__BuildControl__control20(@__ctrl.Items);
            
            #line default
            #line hidden
            
            #line 62 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.itemListBox_SelectedIndexChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2812,
                        387,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3199,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Select an item");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3355,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator3() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RequiredFieldValidator3";
            
            #line default
            #line hidden
            
            #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "itemListBox";
            
            #line default
            #line hidden
            
            #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "Select an item";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 68 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3221,
                        177,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Item Text:</td>\r\n                <td>\r\n                    " +
                    "");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3398,
                        161,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlitemTextBox() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 74 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.itemTextBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 74 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "itemTextBox";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3559,
                        59,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control28() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3618,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control29() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Enter text");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3772,
                        10,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator4() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator4 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RequiredFieldValidator4";
            
            #line default
            #line hidden
            
            #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "itemTextBox";
            
            #line default
            #line hidden
            
            #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "Enter a text";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 75 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3640,
                        171,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control30() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Quantity:</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3811,
                        160,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControlquantityTextBox() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 81 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.quantityTextBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 81 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "quantityTextBox";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3971,
                        63,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4034,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control32() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("*");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4200,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator2() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator2 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RequiredFieldValidator2";
            
            #line default
            #line hidden
            
            #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "quantityTextBox";
            
            #line default
            #line hidden
            
            #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "Enter a valid number";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 82 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4056,
                        174,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control33() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4230,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control34() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Enter a valid number");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4419,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RangeValidator @__BuildControlRangeValidator1() {
            global::System.Web.UI.WebControls.RangeValidator @__ctrl;
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RangeValidator();
            
            #line default
            #line hidden
            this.RangeValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "RangeValidator1";
            
            #line default
            #line hidden
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ControlToValidate = "quantityTextBox";
            
            #line default
            #line hidden
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ErrorMessage = "Enter a valid number";
            
            #line default
            #line hidden
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.MaximumValue = "999999";
            
            #line default
            #line hidden
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.MinimumValue = "1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control34();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 83 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4252,
                        208,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control35() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Order Details:</td>\r\n                <td>\r\n                " +
                    "    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4460,
                        165,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlorderLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 89 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.orderLabel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 89 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "orderLabel";
            
            #line default
            #line hidden
            
            #line 89 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Label";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4625,
                        67,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control36() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4692,
                        124,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControladdOrderButton() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 94 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.addOrderButton = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 94 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "addOrderButton";
            
            #line default
            #line hidden
            
            #line 94 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Add to Order";
            
            #line default
            #line hidden
            
            #line 94 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Click += new System.EventHandler(this.addOrderButton_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4816,
                        100,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control37() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4916,
                        67,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlcompleteOrderButton() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 97 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.completeOrderButton = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 97 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "completeOrderButton";
            
            #line default
            #line hidden
            
            #line 97 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Text = "Complete Order";
            
            #line default
            #line hidden
            
            #line 97 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.Click += new System.EventHandler(this.cmdStore_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4983,
                        101,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control38() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n        </table>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5084,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl2;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl2 = this.@__BuildControlHyperLink1();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl3 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl4 = this.@__BuildControlnameTextBox();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl5 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl6;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl6 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl8 = this.@__BuildControlphoneTextBox();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl9 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl10;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl10 = this.@__BuildControlRegularExpressionValidator1();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl11 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl12;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl12 = this.@__BuildControlRequiredFieldValidator5();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl13 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl14 = this.@__BuildControlcreditCardTextBox();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl15 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl16;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl16 = this.@__BuildControlRegularExpressionValidator2();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl17 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListBox @__ctrl18;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl18 = this.@__BuildControlitemListBox();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl19 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl20;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl20 = this.@__BuildControlRequiredFieldValidator3();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl21;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl21 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl22;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl22 = this.@__BuildControlitemTextBox();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl23;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl23 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl24;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl24 = this.@__BuildControlRequiredFieldValidator4();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl25;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl25 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl25);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl26;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl26 = this.@__BuildControlquantityTextBox();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl26);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl27;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl27 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl27);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl28;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl28 = this.@__BuildControlRequiredFieldValidator2();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl28);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl29;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl29 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl29);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RangeValidator @__ctrl30;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl30 = this.@__BuildControlRangeValidator1();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl30);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl31;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl31 = this.@__BuildControl__control35();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl31);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl32;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl32 = this.@__BuildControlorderLabel();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl32);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl33;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl33 = this.@__BuildControl__control36();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl33);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl34;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl34 = this.@__BuildControladdOrderButton();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl34);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl35;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl35 = this.@__BuildControl__control37();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl35);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl36;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl36 = this.@__BuildControlcompleteOrderButton();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl36);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl37;
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl37 = this.@__BuildControl__control38();
            
            #line default
            #line hidden
            
            #line 27 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl37);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        604,
                        4553,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control39() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5157,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(order_aspx @__ctrl) {
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__ctrl5 = this.@__BuildControl__control39();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Order.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\asp.net\CBauerHW2\Order.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.order_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1502317986;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
