#pragma checksum "E:\asp.net\CBauerHW2\Admin.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "91DBC2C730779C49B03910D70811897D0B856471"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.HyperLink HyperLink1;
    
    #line default
    #line hidden
    
    
    #line 43 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.Label revenueLabel;
    
    #line default
    #line hidden
    
    
    #line 54 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.Label penLabel;
    
    #line default
    #line hidden
    
    
    #line 60 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.Label mouseLabel;
    
    #line default
    #line hidden
    
    
    #line 66 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.Label pictureLabel;
    
    #line default
    #line hidden
    
    
    #line 72 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.Label mugLabel;
    
    #line default
    #line hidden
    
    
    #line 78 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.WebControls.ListBox detailsListBox;
    
    #line default
    #line hidden
    
    
    #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 392 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 399 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 390 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 388 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 394 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 405 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 404 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 395 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 391 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 386 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 393 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 400 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 396 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 387 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 389 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 398 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_aspx : global::Admin, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.admin_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\asp.net\CBauerHW2\Admin.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Admin.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Admin.aspx";
                dependencies[1] = "~/Admin.aspx.cs";
                global::ASP.admin_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        90,
                        68,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Runtime, Version=1.3.0.0, Culture=neutral, Publi" +
                    "cKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.admin_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.admin_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        185,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <style type=""text/css"">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 168px;
            text-align: right;
        }
        .auto-style3
        {
            width: 168px;
            text-align: right;
            height: 25px;
        }
        .auto-style4
        {
            height: 25px;
        }
    </style>
");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        200,
                        401,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 6 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        158,
                        450,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        608,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div>\r\n    \r\n        Admin Page<table class=\"auto-style1\">\r\n            <tr" +
                    ">\r\n                <td class=\"auto-style2\">\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        654,
                        146,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("Homepage");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        875,
                        8,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControlHyperLink1() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            this.HyperLink1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "HyperLink1";
            
            #line default
            #line hidden
            
            #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.NavigateUrl = "~/Default.aspx";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 35 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        800,
                        99,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n                <td>\r\n                    &nbsp;</td>\r\n " +
                    "           </tr>\r\n            <tr>\r\n                <td class=\"auto-style3\">Reve" +
                    "nues:</td>\r\n                <td class=\"auto-style4\">\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        899,
                        235,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlrevenueLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 43 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.revenueLabel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 43 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "revenueLabel";
            
            #line default
            #line hidden
            
            #line 43 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.Text = "Label";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1134,
                        69,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                </td>
            </tr>
            <tr>
                <td class=""auto-style2"">Sales</td>
                <td>
                    &nbsp;</td>
            </tr>
            <tr>
                <td class=""auto-style2"">pens:</td>
                <td>
                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1203,
                        300,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlpenLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 54 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.penLabel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 54 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "penLabel";
            
            #line default
            #line hidden
            
            #line 54 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.Text = "Label";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1503,
                        65,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">mouse pads:</td>\r\n                <td>\r\n                   " +
                    " ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1568,
                        162,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlmouseLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 60 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.mouseLabel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 60 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "mouseLabel";
            
            #line default
            #line hidden
            
            #line 60 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.Text = "Label";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1730,
                        67,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">picture frame:</td>\r\n                <td>\r\n                " +
                    "    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1797,
                        165,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlpictureLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 66 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.pictureLabel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 66 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "pictureLabel";
            
            #line default
            #line hidden
            
            #line 66 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.Text = "Label";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1962,
                        69,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">mug:</td>\r\n                <td>\r\n                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2031,
                        155,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlmugLabel() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 72 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.mugLabel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 72 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "mugLabel";
            
            #line default
            #line hidden
            
            #line 72 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.Text = "Label";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2186,
                        65,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">Customer Details:</td>\r\n                <td>\r\n             " +
                    "       ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2251,
                        168,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListBox @__BuildControldetailsListBox() {
            global::System.Web.UI.WebControls.ListBox @__ctrl;
            
            #line 78 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListBox();
            
            #line default
            #line hidden
            this.detailsListBox = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 78 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "detailsListBox";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2419,
                        62,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <td" +
                    " class=\"auto-style2\">&nbsp;</td>\r\n                <td>&nbsp;</td>\r\n            <" +
                    "/tr>\r\n        </table>\r\n    \r\n    </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2481,
                        207,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl2;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl2 = this.@__BuildControlHyperLink1();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl3 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl4;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl4 = this.@__BuildControlrevenueLabel();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl5 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl6;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl6 = this.@__BuildControlpenLabel();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl7 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl8;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl8 = this.@__BuildControlmouseLabel();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl9 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl10;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl10 = this.@__BuildControlpictureLabel();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl11 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl12;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl12 = this.@__BuildControlmugLabel();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl13 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListBox @__ctrl14;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl14 = this.@__BuildControldetailsListBox();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl15 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 29 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        622,
                        2073,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2695,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_aspx @__ctrl) {
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl4;
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl4 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__ctrl5 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 1 "E:\asp.net\CBauerHW2\Admin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\asp.net\CBauerHW2\Admin.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 278066097;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
